### ISSUE TITLE
Needs moar yarn.

### ISSUE THREAD

**Issue by moottoast** [anhari/bob-loblaws-law-blog#1]
Yarn all the things.

**Comment by anhari** [comment]
Way head of you:

https://github.com/anhari/bob-loblaws-law-blog/commit/bee4c5d99f8744d5c6850cde457e8e211be81d2c

**Comment by anhari** [comment]
Fixed with: https://github.com/anhari/bob-loblaws-law-blog/commit/bee4c5d99f8744d5c6850cde457e8e211be81d2c
